version: '3.8'

services:
  api:
    image: resync-fullstack-test
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
    networks:
      - backend
    volumes:
      - ./backend:/usr/src/app
  db:
    image: mysql:8
    container_name: resync_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./backend/data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
networks:
  backend:
    driver: bridge
